### 🤖 Guía de Asistencia con IA: IA como Copiloto de Programación

En esta notebook, utilizaremos la Inteligencia Artificial como copiloto de aprendizaje. Aquí tienes algunas sugerencias de cómo interactuar con un asistente de IA (como Gemini o ChatGPT):

- **Explicación de código**: Si encuentras una función o línea que no comprendes, pregúntale a la IA: *'Explica qué hace esta función línea por línea en Python: [pega tu código]'*.
- **Corrección de errores**: Si tienes un error al ejecutar, copia el error completo y pregúntale: *'¿Por qué este código genera este error y cómo lo soluciono? [pega tu código y error]'*.
- **Optimización**: Pregunta: *'¿Cómo puedo escribir este código de forma más eficiente y limpia?'*.


# Programa Ingenias+ Data Science

In [1]:
import pandas as pd
expvida = pd.read_csv('life_expectancy_data.csv')

In [2]:
#Importar numpy
import numpy as np

In [3]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [4]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [5]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [6]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [7]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [8]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.40358659 0.88903078 0.23517592 0.53090894 0.86676149 0.31721516
 0.91790323 0.53685888 0.67777734 0.84040846 0.88938769 0.62529757
 0.43176578 0.14574152 0.59865565 0.15033915 0.50540803 0.94678193
 0.64640867 0.87746519 0.73049869 0.53003071 0.45862108 0.70698863
 0.62203192 0.1991902  0.81505392 0.51132398 0.937191   0.09376731
 0.72091278 0.48251684 0.21160158 0.62422414 0.31053244 0.22729789
 0.73124649 0.92109467 0.35034203 0.16200131 0.16701878 0.86806707
 0.91750068 0.34364345 0.8399201  0.21312606 0.48100579 0.18487687
 0.60890556 0.32887814 0.58766743 0.85685506 0.69675677 0.44470489
 0.2810628  0.30331508 0.97340225 0.3923057  0.57791847 0.47967306
 0.63504377 0.33301759 0.41320367 0.90987975 0.48487148 0.05979847
 0.82326288 0.51004486 0.40416725 0.20655801 0.70986209 0.32316985
 0.90409729 0.86928167 0.9155279  0.14480567 0.09606631 0.78751169
 0.39881452 0.57880329 0.0803661  0.95988805 0.75380063 0.38416135
 0.75382699 0.60617305 0.2346129  0.65127355 0.20411273 0.0414

In [11]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.77745889 0.06269832 0.87528603 0.50062311 0.93708971 0.90321163
 0.62180086 0.80343437 0.03640785 0.92630553 0.47483888 0.49286334
 0.05057976 0.85544736 0.7321428  0.88970372 0.02052385 0.08541266
 0.458911   0.31956251 0.87070854 0.15766289 0.8518042  0.23325952
 0.30173205]

Media: 0.5295787753694493

Varianza: 0.10816038594273021


In [12]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.54200184]


In [13]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)

[0.52957878]


In [14]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.07081448]


In [15]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.96598979 0.59932545 0.79367816 0.88091182 0.12783712 0.10801558
 0.76438339 0.19107217 0.06764947 0.37338802 0.00631387 0.42832053
 0.9791344  0.20443153 0.3048075 ]
